### PR TITLE
feat: add opensearch

### PR DESCRIPTION
**Pull request by t1st3**
as described in #31

### CODE REVIEW

**Comment by freeall** [comment]
lgtm
@mafintosh what do you think?

**Comment by t1st3** [comment]
bump @mafintosh

**Comment by t1st3** [comment]
Sorry to insist on this... @mafintosh do you have any thoughts about this PR? Let's merge or close!

**Comment by mafintosh** [comment]
looks good

**Comment by t1st3** [comment]
It's actually already working live! Great!
Thanks for merging, and sorry again to have insisted on this

**Comment by mafintosh** [comment]
np, thanks for the reminder

**Pull request merged**
